# Book settings
title: Deep learning classification from brain MRI
author: The Aramis Team
logo: 'images/logo1.png'
description: Tutorial for the deep learning classification from brain MRI

launch_buttons:
  colab_url: "https://colab.research.google.com"
   # jupyterhub_url: "localhost:8080"  # The URL for your JupyterHub. (e.g., https://datahub.berkeley.edu)

######################################################################################
# Execution settings
execute:
  execute_notebooks         : "off"  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

html:
  #favicon: images/favicon.ico
  google_analytics_id: UA-173464732-1 
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://aramislab.paris.inria.fr/clinicadl/tuto/

repository:
  url: https://github.com/aramis-lab/MICCAI-educational-challenge-2020/
  branch: master

sphinx:
  config:
    mathjax_config:
      TeX:
        Macros:
          "N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat": ["\\left[\\begin{array}"]
          "emat": ["\\end{array}\\right]"]
  extra_extensions:
    - sphinx_click.ext
    - sphinx_tabs.tabs
