# Book settings
title: Deep learning for Medical Imaging
author: The Aramis Team
logo: 'images/logoAramis.png'
description: Tutorial for the deep learning classification from brain MRI

exclude_patterns:
  -  _build
  - Thumbs.db
  - .DS_Store
  - "**.ipynb_checkpoints"
  - "figures"
  - "datasets"
  - "README.md"

repository:
  url: https://github.com/aramis-lab/DL4MI 
  path_to_book: jupyter-book/
  branch: main

launch_buttons:
  notebook_interface: classic
  colab_url: https://colab.research.google.com
  #jupyterhub_url: "localhost:8080"  # The URL for your JupyterHub. (e.g., https://datahub.berkeley.edu)

######################################################################################
# Execution settings
execute:
  execute_notebooks         : cache  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns:
    - 

html:
  #favicon: _static/favicon.ico
  google_analytics_id: UA-173464732-1 
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://aramislab.paris.inria.fr/clinicadl/DL4MI/


sphinx:
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py:percent
    mathjax_config:
      TeX:
        Macros:
          "N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat": ["\\left[\\begin{array}"]
          "emat": ["\\end{array}\\right]"]
  extra_extensions:
    - sphinx_click.ext
    - sphinx_tabs.tabs


latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex     
